#!/bin/sh

# reset database
rake db:migrate:reset

# delete keyring
rm  ../.gnupg/pubring.gpg
rm  ../.gnupg/secring.gpg

# create blank key rings
gpg --list-keys
gpg --list-secret-keys

# implant database seeds
rake db:seed
